#version: "3.3"
#services:
#  tracker:
#    container_name: tracker
#    build:
#      context: .
#      dockerfile: ./tracker/Dockerfile
#    working_dir: /tracker
#    entrypoint: ["./tracker"]
#    networks:
#      bittorrent:
#        ipv4_address: 192.168.20.10
##    command: tail -f /dev/null
#  peer1:
#    container_name: peer1
#    build:
#      context: .
#      dockerfile: ./peer/Dockerfile
#    working_dir: /peer
#    stdin_open: true
#    tty: true
#    command: bash -c "sleep 2 && ./peer"
#    networks:
#      bittorrent:
#        ipv4_address: 192.168.20.11
##    command: tail -f /dev/null
#  peer2:
#    container_name: peer2
#    build:
#      context: .
#      dockerfile: ./peer/Dockerfile
#    working_dir: /peer
#    stdin_open: true
#    tty: true
#    command: bash -c "sleep 2 && ./peer"
#    networks:
#      bittorrent:
#        ipv4_address: 192.168.20.12
##    command: tail -f /dev/null
#  peer3:
#    container_name: peer3
#    build:
#      context: .
#      dockerfile: ./peer/Dockerfile
#    stdin_open: true
#    tty: true
#    working_dir: /peer
#    command: bash -c "sleep 2 && ./peer"
#    networks:
#      bittorrent:
#        ipv4_address: 192.168.20.13
##    command: tail -f /dev/null
#networks:
#  bittorrent:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 192.168.20.0/24


version: "3.3"
services:
  tracker:
    container_name: tracker
    build:
      context: .
      dockerfile: ./tracker/Dockerfile
    working_dir: /tracker
#    entrypoint: ["./tracker"]
    networks:
      bittorrent:
        ipv4_address: 192.168.20.10
    command: tail -f /dev/null
  peer1:
    container_name: peer1
    build:
      context: .
      dockerfile: ./peer/Dockerfile
    working_dir: /peer
    stdin_open: true
    tty: true
#    command: bash -c "sleep 2 && ./peer"
    networks:
      bittorrent:
        ipv4_address: 192.168.20.11
    command: bash -c "echo "123" > plik && tail -f /dev/null"
  peer2:
    container_name: peer2
    build:
      context: .
      dockerfile: ./peer/Dockerfile
    working_dir: /peer
    stdin_open: true
    tty: true
#    command: bash -c "sleep 2 && ./peer"
    networks:
      bittorrent:
        ipv4_address: 192.168.20.12
    command: tail -f /dev/null
#  peer3:
#    container_name: peer3
#    build:
#      context: .
#      dockerfile: ./peer/Dockerfile
#    stdin_open: true
#    tty: true
#    working_dir: /peer
##    command: bash -c "sleep 2 && ./peer"
#    networks:
#      bittorrent:
#        ipv4_address: 192.168.20.13
#    command: tail -f /dev/null
networks:
  bittorrent:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24